# Development profile properties
spring.thymeleaf.cache=false
logging.level.org.springframework.context.annotation=DEBUG
logging.level.org.springframework.boot.web.embedded.tomcat=DEBUG
logging.level.org.springframework.jdbc=DEBUG
rate.limit.capacity=30
rate.limit.time=1
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.platform=h2
