CREATE TABLE IF NOT EXISTS SALES_DATA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    product VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    revenue DOUBLE NOT NULL
);